#!/bin/env bash

setxkbmap es &
feh --bg-scale $HOME/media/pics/walls/current --no-fehbg &
picom -f &
dunst &
xset r rate 300 50 &
sudo redshift -l 41.452943:2.056726 &
bat &
rsblocks &

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

exec dwm
